# Generated by Django 4.2.7 on 2023-11-28 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_importance_task_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='importance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='note.importance'),
        ),
    ]
